"""add is_active to users

Revision ID: 46e304a435af
Revises: bf91942979ac
Create Date: 2026-06-11 14:33:29.819796

"""
from alembic import op
import sqlalchemy as sa

revision = '46e304a435af'
down_revision = 'bf91942979ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###