"""init

Revision ID: 7769fb4e17f3
Revises: 83ca0b670fef
Create Date: 2026-06-11 14:27:05.808881

"""
from alembic import op
import sqlalchemy as sa

revision = '7769fb4e17f3'
down_revision = '83ca0b670fef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###