"""init

Revision ID: 83ca0b670fef
Revises: 392b7b07acb1
Create Date: 2026-06-11 14:12:32.989374

"""
from alembic import op
import sqlalchemy as sa

revision = '83ca0b670fef'
down_revision = '392b7b07acb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###